"""Test fixtures and constants for the Java engine core, produced by python-chess.

python-chess is an independent implementation of the rules and of the Polyglot hash, so what
it says is a fair referee for the Java board code. This writes three things:

  * PolyglotZobrist.java     - the 781 Polyglot random numbers, so none is typed by hand
  * polyglot-keys.csv        - FEN,key for random positions
  * legal-moves.csv          - FEN,sorted UCI legal moves for the same positions
  * mates.csv                - FEN,N,moves: positions where White forces mate in N moves
                               (shortest N, brute-forced), with every first move that does it

Run from the training folder with the venv active:

    .venv\\Scripts\\python engine_fixtures.py
"""
from __future__ import annotations

import random
from pathlib import Path

import chess
import chess.polyglot as polyglot

ROOT = Path(__file__).resolve().parent.parent
MAIN = ROOT / "chess-engine" / "src" / "main" / "java" / "com" / "chess" / "engine" / "core"
RESOURCES = ROOT / "chess-engine" / "src" / "test" / "resources" / "engine"

POSITIONS = 400
SEED = 20261006


def write_zobrist() -> None:
    values = polyglot.POLYGLOT_RANDOM_ARRAY
    assert len(values) == 781
    lines = []
    for i in range(0, 781, 3):
        chunk = ", ".join(f"0x{v:016X}L" for v in values[i:i + 3])
        lines.append(f"        {chunk},")
    body = "\n".join(lines)
    text = f'''package com.chess.engine.core;

/**
 * The 781 random numbers of the Polyglot opening-book format, in book order:
 * 768 piece-square numbers (64 * kind + 8 * row + file, kind = 2 * type + (white ? 1 : 0)),
 * then 4 for castling rights (K, Q, k, q), 8 for en passant files, and 1 for white to move.
 *
 * Generated by training/engine_fixtures.py from python-chess; do not edit by hand.
 */
final class PolyglotZobrist {{

    private PolyglotZobrist() {{}}

    static final long[] RANDOM = {{
{body}
    }};
}}
'''
    MAIN.mkdir(parents=True, exist_ok=True)
    (MAIN / "PolyglotZobrist.java").write_text(text, encoding="utf-8", newline="\n")
    print("wrote PolyglotZobrist.java")


def random_positions(count: int, rng: random.Random) -> list[chess.Board]:
    """Positions from random playouts, including the awkward ones: promotions, castling, en passant."""
    seeds = [
        "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1",   # Kiwipete
        "8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1",                                  # perft position 3
        "r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1",          # position 4
        "rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8",                  # position 5
        "r4rk1/1pp1qppp/p1np1n2/2b1p1B1/2B1P1b1/P1NP1N2/1PP1QPPP/R4RK1 w - - 0 10",   # position 6
        "4k3/8/8/8/8/8/4P3/4K3 w - - 0 1",
        "8/P7/8/8/8/8/8/k6K w - - 0 1",
    ]
    boards: list[chess.Board] = []
    for fen in seeds:
        boards.append(chess.Board(fen))
    while len(boards) < count:
        board = chess.Board()
        for _ in range(rng.randint(0, 120)):
            moves = list(board.legal_moves)
            if not moves or board.is_game_over():
                break
            board.push(rng.choice(moves))
        if board.is_game_over():
            continue
        boards.append(board)
    return boards[:count]


def fen_with_ep(board: chess.Board) -> str:
    """FEN with the en passant square shown after every double push, as the Java side prints it."""
    return board.fen(en_passant="fen")


def write_csvs() -> None:
    rng = random.Random(SEED)
    boards = random_positions(POSITIONS, rng)
    RESOURCES.mkdir(parents=True, exist_ok=True)
    keys, moves = [], []
    for board in boards:
        fen = fen_with_ep(board)
        keys.append(f"{fen},{polyglot.zobrist_hash(board):016x}")
        uci = sorted(m.uci() for m in board.legal_moves)
        moves.append(f"{fen},{' '.join(uci)}")
    (RESOURCES / "polyglot-keys.csv").write_text("\n".join(keys) + "\n", encoding="utf-8", newline="\n")
    (RESOURCES / "legal-moves.csv").write_text("\n".join(moves) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {len(boards)} positions to {RESOURCES}")


def can_mate(board: chess.Board, n: int) -> bool:
    """Can the side to move force checkmate within n of its own moves? (brute force)"""
    if n <= 0:
        return False
    for move in list(board.legal_moves):
        board.push(move)
        if board.is_checkmate():
            board.pop()
            return True
        mated = False
        if n > 1 and not board.is_game_over():
            mated = all(_after_reply(board, reply, n - 1) for reply in list(board.legal_moves))
        board.pop()
        if mated:
            return True
    return False


def _after_reply(board: chess.Board, reply: chess.Move, n: int) -> bool:
    board.push(reply)
    result = can_mate(board, n)
    board.pop()
    return result


def first_moves_mating(board: chess.Board, n: int) -> list[str]:
    """Every move after which White still mates within n moves (counting that move)."""
    winners = []
    for move in list(board.legal_moves):
        board.push(move)
        ok = board.is_checkmate() or (
            n > 1 and not board.is_game_over()
            and all(_after_reply(board, reply, n - 1) for reply in list(board.legal_moves)))
        board.pop()
        if ok:
            winners.append(move.uci())
    return sorted(winners)


def random_endgame(rng: random.Random) -> chess.Board | None:
    material = rng.choice([
        [chess.QUEEN], [chess.ROOK], [chess.ROOK, chess.ROOK], [chess.QUEEN, chess.ROOK],
        [chess.ROOK, chess.BISHOP], [chess.QUEEN, chess.KNIGHT], [chess.QUEEN, chess.QUEEN],
    ])
    board = chess.Board(None)
    squares = rng.sample(range(64), 2 + len(material) + rng.choice([0, 0, 1]))
    board.set_piece_at(squares[0], chess.Piece(chess.KING, chess.WHITE))
    board.set_piece_at(squares[1], chess.Piece(chess.KING, chess.BLACK))
    for sq, piece_type in zip(squares[2:], material):
        board.set_piece_at(sq, chess.Piece(piece_type, chess.WHITE))
    if len(squares) > 2 + len(material):                        # sometimes a black pawn for company
        sq = squares[-1]
        if chess.square_rank(sq) in (0, 7):
            return None
        board.set_piece_at(sq, chess.Piece(chess.PAWN, chess.BLACK))
    board.turn = chess.WHITE
    if not board.is_valid() or board.is_check() or board.is_game_over():
        return None
    return board


def write_mates(per_length: int = 12) -> None:
    import time
    rng = random.Random(SEED + 1)
    found: dict[int, list[str]] = {1: [], 2: [], 3: []}
    deadline = time.time() + 240
    attempts = 0
    while time.time() < deadline and any(len(v) < per_length for v in found.values()):
        attempts += 1
        board = random_endgame(rng)
        if board is None:
            continue
        length = next((n for n in (1, 2, 3) if can_mate(board, n)), None)
        if length is None or len(found[length]) >= per_length:
            continue
        moves = first_moves_mating(board, length)
        found[length].append(f"{fen_with_ep(board)},{length},{' '.join(moves)}")
    RESOURCES.mkdir(parents=True, exist_ok=True)
    rows = [row for n in (1, 2, 3) for row in found[n]]
    (RESOURCES / "mates.csv").write_text("\n".join(rows) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote mates.csv: " + ", ".join(f"mate in {n}: {len(found[n])}" for n in (1, 2, 3)) + f" ({attempts} candidates)")


if __name__ == "__main__":
    write_zobrist()
    write_csvs()
    write_mates()
